<CheckBoxLayout>:

    Label:
        id: checkbox_output_label
        text: ""

    GridLayout:
        cols:2

        Label:
            text: "Pepperoni"
            font_size:20
        CheckBox:
            on_active: root.checkbox_click(self, self.active, "Pepperoni")

        Label:
            text: "Cheese"
            font_size:20
        CheckBox:
            on_active: root.checkbox_click(self, self.active, "Cheese")
