#:kivy 1.8.1
#:include button.kv

<CustomLayout>:
    GridLayout:
        rows: 2

        GridLayout:
            cols: 2
			rows: 1
			size_hint: 1, 0.1

            SpecialButton:
                text: 'Includes!'
                size_hint: 1, 1
            ExitButton:
                text: 'Exit'
                size_hint: 0.1, 1

        BoxLayout:
            size_hint: 1, 0.9

            CheckBoxLayout
#                text: "Pepperoni"

#            GridLayout:
#                cols:2
#
#                Label:
#                    text: "Pepperoni"
#                    font_size:20
#                CheckBox:
#                    on_active: root.checkbox_click(self, self.active, "Pepperoni")
#
#                Label:
#                    text: "Cheese"
#                    font_size:20
#                CheckBox:
#                    on_active: root.checkbox_click(self, self.active, "Cheese")


            Accordion:
                orientation: 'vertical'
                pos_hint: {'top': 1}

                AccordionItem:
                    title: 'Panel1'
                    collapse: False

                AccordionItem:
                    title: 'Panel2'


                AccordionItem:
                    title: 'Panel3'
